# Generated by Django 3.1.7 on 2021-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AddField(
            model_name='users',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
