# Generated by Django 3.1.7 on 2021-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20210624_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='p_pic',
            field=models.ImageField(default='/static/img/avatar-15.png', upload_to='profilepics/'),
        ),
    ]
