# Generated by Django 3.1.7 on 2021-06-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_users_p_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='p_pic',
            field=models.ImageField(default='profile-pics/avatar-15.png', upload_to='profilepics/'),
        ),
    ]
