# Generated by Django 3.1.7 on 2021-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20210609_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_ride',
            old_name='dcod',
            new_name='dlat',
        ),
        migrations.RenameField(
            model_name='offer_ride',
            old_name='scod',
            new_name='dlon',
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='slat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='slon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
