# Generated by Django 3.1.7 on 2021-07-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_auto_20210609_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_ride',
            name='offer_maker',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
