# Generated by Django 3.1.7 on 2021-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('dest', models.TextField()),
                ('cap', models.IntegerField()),
                ('slon', models.FloatField()),
                ('slat', models.FloatField()),
                ('dlon', models.FloatField()),
                ('dlat', models.FloatField()),
                ('ride_num', models.IntegerField()),
            ],
        ),
    ]
