# Generated by Django 3.1.7 on 2021-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_rides',
            name='ride_taker',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
