# Generated by Django 3.1.7 on 2021-07-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_p_rides_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_rides',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
